### ISSUE TITLE
Epic - Image Management 

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#102]
This Epic capture the work to provide Image Management

## Plan Items
Please list the items to be covered. Create an issue for each and link it with the # syntax

### Deploy

- [x] Create a base CentOS 7.8 HPC image for CPU only nodes #103
- [x] Update the pipeline to build the azhop-centos78 image #104
- [x] Integrate the Shared Image Gallery #63
- [x] Create Image definition from TF #113
- [x] Add a force option on the build image #115
