### ISSUE TITLE
Iteration plan for V0.1.0

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#155]
This plan capture our work to prepare the release 0.1.0

### Applications
- [ ] Epic for Recipes and documentation on how to run WRF #158

### Cycle Cloud Integration
- [x] Use AD with CycleCloud #139
- [x] use scalelib for autoscaling #156
- [x] Enable access to Cycle Cloud portal from OOD #170
- [x] Non admin users should have Read/Only access to the Cycle Portal #178
- [x] Rebrand Azure CycleCloud to AZHOP CycleCloud #189
- [x] Add a link/menu to access to CycleCloud from the OOD Portal #213
- [x] update scalelib hook to be called every minutes instead of 15s #219
- [x] Integrate CycleCloud 8.1.1 #231

### Improvments
- [x] As a end user how do I understand why my job is waiting ? #69
- [x] Provide a way for an end user to know which slot types are available #68
- [x] rename OOD _my_cluster to something more appropriate #67
- [x] Rebrand the OOD page with Azure HPC On-Demand Platform #66
- [x] Add a link to grafana from the ood page #32
- [x] Option to allow sudo for users #28
- [x] Add a read only account to the keyvault storing secrets #168
- [x] Add python3 in images #186
- [x] Limit the value of number of hours of the remote session #226

### CI/CD
- [x] Create the integration pipeline #157
- [x] Upgrade YQ to version 4.6.0 #134
- [x] Add basic functional testing #163
- [x] Build image only if scripts used to build the image have changed #164
- [x] Updating image id in Cycle project need to be done after the image have been built #200
- [x] Create a production deployment pipeline #233

### Bug to be Fixed
- [x] AN is set to active by default #132
- [x] nodes are failing to register to PBS #118
- [x] Cycle is not scaling to more than a single viz3d VM #57
- [x] vglrun not working with remote desktop #55
- [ ] Packer is not failing when an installation script failed #151
- [x] Error when building on top of an existing deployment #167
- [x] PBS autostart.py no longer exists #179
- [x] Remote session is not taking in acount the max hour defined #195
- [ ] wrong status of viz3d VM in Cycle #193
- [x] Autoscaling doesn't work when mixing interactive and batch jobs #201
- [ ] Grafana is not reporting compute node data #202
- [x] scalelib : qstat: PBS is not configured to maintain job history #208
- [x] scalelib is not always unregistering nodes from PBS #218
