### ISSUE TITLE
Epic - Users and Right management

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#192]
## Describe the feature

- [x] make az-hop admins cycle admins #234
- [x] implement users groups #235
- [x] add a new user to an existing system #236
- [ ] remove an existing user from an existing system #237
- [ ] allow users to change their password #238
- [ ] allow users to change their password upon first connection #239
