### ISSUE TITLE
Iteration plan for V1.0.0

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#230]
This plan capture our work to prepare the 1.0.0 release

### Applications
- [x] Epic for Recipes and documentation on how to run OpenFoam #99
- [ ] Epic for Recipes and documentation on how to run WRF #158

### Cycle Cloud Integration
- [x] separate PBS project setup from the core CycleCloud ansible role #61
- [x] Add a healthcheck for GPU nodes #270
- [ ] Enabled Accelerated network on HPC SKU's #271
- [ ] make az-hop admins cycle admins #234

### Improvments
- [ ] remove the ansible password from the inventory file #65
- [ ] Check for az-hop prerequisites #124
- [x] Add readthedocs documentations #321
- [ ] check susbscription pre-requisities before deploying #320
- [ ] be able to deploy as a subscription contributor and not a owner #317
- [ ] provide a set of pre-defined configuration #319
- [x] deny access to sensitive files for non admin users #318
- [ ] Add a page with all the software version deployed #259 
- [ ] When building an image use the offer, publisher, sku and version from the config file #275

### Bug to be Fixed
- [x] enable log rotation on the scheduler #315
