### ISSUE TITLE
Iteration plan for Preparation of Hackathon Feb 2021

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#70]
This plan capture our work to prepare the Mid-February hackathon

#### Shared Environment

- [x] Create a Pipeline to deploy the shared environment #71 @xpillons 
- [x] implement a private persistent storage for pipeline artifacts #76 @xpillons 
- [x] In the integration pipeline, don't rebuild images if they exists #90 

#### Deploy your Own

- [x] Review and correct the instructions in the Readme to deploy an environment #72 @edwardsp @hmeiland 
- [x] Review and correct instructions on how to access CycleCloud and Grafana #73 @edwardsp @hmeiland 
- [x] Add instructions on how to access the cluster #74 @edwardsp @hmeiland 

### Improvment

- [x] Cycle compute VMs should `chmod 777` on /mnt/resource #77 
- [x] Disable AN for Cycle compute nodes #78 
- [x] Create a different password per user #82 @xpillons 
- [x] AD security enforcement #83
